### ISSUE TITLE
JUnit run configuration cannot be generated correctly

### ISSUE THREAD

**Issue by rszulgo** [rodionmoiseev/gradle-plugins#13]
Following configuration :
JUnitTestMyApp {
    type = 'Junit'
    factoryName = 'Junit'
    ....
}

generates the ipr : 
    <configuration default="false" name="Run All JUnit tests" type="Junit" factoryName="Junit">

"Junit" value is invalid - it should be "JUnit" (with capital "JU")

**Comment by rszulgo** [comment]
fixed in my fork

**Comment by rodionmoiseev** [comment]
Thanks! Can you submit a pull req. please?

**Comment by rszulgo** [comment]
yes, sure:;)

2015-02-10 1:39 GMT+01:00 Rodion Moiseev <notifications@github.com>:

**Comment by rodionmoiseev** [comment]
Closed by #14
